version: '3.7'

services:
  bulky_db:
    image: postgres:latest
    container_name: bulky_db
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - bulky_db_data:/var/lib/postgresql/data/
volumes:
  bulky_db_data: